### PR TITLE
Release/0.0.2

### PR DESCRIPTION
**Pull request by AdrianKonca**
In this release:
- Basic path-finding
- Day and night cycle
- Furniture building
- Building interface
- Basic Appearance generator
- Adds selection cursor
- Adds building cursor
- Adds deconstruction cursor

### CODE REVIEW

**Review by mm44419 — APPROVED** [review]
We are going into some places. Nice job

**Review by SebastianRatanczuk — APPROVED** [review]
Ok jest git

**Review by Krystian1222 — COMMENTED** [review]
Jest ok.

**Review by mm44419 — COMMENTED** [review]
Ok

**Pull request merged**
