### PR TITLE
Release/0.0.1

### PR DESCRIPTION
**Pull request by AdrianKonca**
Includes:

- Basic camera movement
- Basic wall building system
- Basic wall system
- Basic sickness calculation

### CODE REVIEW

**Comment by SebastianRatanczuk** [comment]
Niezdecydowany seba 
image
image

**Comment by SebastianRatanczuk** [comment]
Ok. Zaliczam

**Review by SebastianRatanczuk — APPROVED** [review]
Ok. Zaliczam

**Comment by mm44419** [comment]
Agree, **keep going** (y)

**Review by mm44419 — APPROVED** [review]
**Good job**, guys, keep going ;)

**Comment by Krystian1222** [comment]
Ok. Zaliczam.

**Pull request merged**
